name: shakespeare-sass
version: '0.1.0.4'
synopsis: SASS support for Shakespeare and Yesod
description: SASS support for Shakespeare and Yesod
category: Web
author: Filip Brcic
maintainer: brcha@yandex.com
license: BSD3
github: brcha/shakespeare-sass
extra-source-files:
- README.md
default-extensions:
- TemplateHaskell
- QuasiQuotes
dependencies:
- base >=4 && <5
- template-haskell
- yesod >=1.4.1 && <1.5.0
- yesod-core >=1.4.6 && <1.5.0
- shakespeare >=2.0 && <2.1
- hsass >=0.2.0 && <0.5.0
library:
  source-dirs: src
  exposed-modules:
  - Text.Shakespeare.Sass
